### ISSUE TITLE
Crate isn't updated on crates.io

### ISSUE THREAD

**Issue by PipInSpace** [grovesNL/glyphon#63]
I have tried using glyphon in a project with wgpu 0.18.0, but it appears that the crate still depends on wgpu 0.16.3, breaking a lot of things. I have seen the `update wgpu to 0.18` commit, but this change doesn't seem to have landed at https://crates.io/crates/glyphon yet (And not on my end either). 
I apologize if this is intentional, but it seems strange to me. Thank you!

**Comment by grovesNL** [comment]
That's intentional for now because we haven't released a new version of glyphon on crates.io yet. You can use a git reference in your Cargo.toml if you want to start using it right away though. We'll publish a new version soon but wanted to make a couple changes first.

**Comment by grovesNL** [comment]
@darthdeus yeah that's a good point. In general if this kind of thing is blocking from anyone publishing please let me know and I'd be happy to try to make a release soon if it makes sense. Otherwise I'd recommend using `[patch.crates-io]` to use a specific git commit (either here or your own fork) until we make a release.

**Comment by grovesNL** [comment]
0.4 has been released:

- https://crates.io/crates/glyphon
- https://github.com/grovesNL/glyphon/releases/tag/0.4
